#!/bin/bash
cd "$(git rev-parse --show-toplevel)"
STAGED_FILES=($(git diff --cached --name-only --diff-filter=ACM))

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

echo ">>> POST-COMMIT Staged Files: ${STAGED_FILES[@]}"
git reset -q "${STAGED_FILES[@]}"
exit 0